version: '2.3'
services:
  lab:
    container_name: jupyter-docker
    
    build:
      context: ./docker-files/jupyter-lab/
    
    ports:
      - "8889:8889"
      - "8050:8050"
      - "8888:8888"
      - "5000:5000"
    volumes: 
      - ./:/user_files
  
    command:  jupyter lab --allow-root --notebook-dir= user_files/ --ip=0.0.0.0 --port=8889 --no-browser
